### ISSUE TITLE
Is it possible to use nuxthub cli in GitHub Actions?

### ISSUE THREAD

**Issue by stonega** [nuxt-hub/cli#15]
If so, is there any documentation or examples available that demonstrate how to set it up?

**Comment by Atinux** [comment]
It is possible but not documented yet.

It should be the same as using any [Node.js CI action](https://github.com/marketplace/actions/setup-node-js-environment) + running `npx nuxthub deploy` with a 2 env variables:
- `NUXT_HUB_PROJECT_KEY` that you can get in your project settings
- `NUXT_HUB_USER_TOKEN` that you can create by cliking on your username in the admin -> Settings -> Tokens

![CleanShot 2024-06-25 at 23 50 20@2x](https://github.com/nuxt-hub/cli/assets/904724/fefd407c-c848-46fe-b96f-807f139cebbe)

Also released [v0.5.13](https://github.com/nuxt-hub/cli/releases/tag/0.5.13) of the CLI so it should work properly with the env variables.

Would love your feedback on this!

**Comment by stonega** [comment]
Thanks, works like a charm
```
      - name: Nuxthub deploy
        run: npx nuxthub deploy
        env:
          NUXT_HUB_PROJECT_KEY: ${{ secrets.NUXT_HUB_PROJECT_KEY}}
          NUXT_HUB_USER_TOKEN: ${{ secrets.NUXT_HUB_USER_TOKEN }}
```

**Comment by Atinux** [comment]
Would you mind sharing your whole Github action so I could write it in the readme or in the docs?

**Comment by Atinux** [comment]
(re-opening to keep it to do)

**Comment by stonega** [comment]
@Atinux  It is pretty simple, just pnpm install && deploy.
```
name: Deploy to Cloudflare with NuxtHub Cli

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install
      
      - name:  Deploy with nuxt-hub cli
        run: npx nuxthub deploy
        env:
          NUXT_HUB_PROJECT_KEY: ${{ secrets.NUXT_HUB_PROJECT_KEY}}
          NUXT_HUB_USER_TOKEN: ${{ secrets.NUXT_HUB_USER_TOKEN }}
```
